[profile.default]
optimizer = true
optimizer_runs = 10_000
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
remappings = [
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'solmate/=node_modules/solmate/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config